### ISSUE TITLE
[ANCHOR-630] SEP-24 asset and amount related request parameters are not working correctly 

### ISSUE THREAD

**Issue by Ifropc** [stellar/java-stellar-anchor-sdk#1286]
### What version are you using?

Latest version

### What did you do?

Make a SEP-24 request (withdrawal/deposit)

### What happened?

When making a request, we accept 4 parameters related to the user desired payment:
* `asset_code`
* `asset_issuer`
* `amount`
* `destination_asset`
* `source_asset`

Each of this parameters should **either** be
1. Stored in DB and be accessible as a field in Platform Transaction object (example: request's `account` for deposit stored as `to_account` and available in Platform Transaction's `destination_account`)
2. Always forwarded in JWT (example: `lang` parameter) 

Current status of this fields:

| Field  | Stored in DB | Field in Platform Transaction | Forwarded in JWT | Consistent 
| ------------- | ------------- |  ------------- | ------------- |  ------------- |
| `asset_code`  |  `asset_code` | `amount_expected.asset`  | no  | :white_check_mark: 
| `asset_issuer`  |  `asset_issuer`   | `amount_expected.asset`  |  no | :white_check_mark: 
| `amount`  | **NO**  | `amount_expected.amount`  | yes  | :x: 
| `destination_asset`  | **NO (unless quote_id is provided)**  |  **NO** | **NO**  | :x: 
| `source_asset`  | **NO (unless quote_id is provided)**  |  **NO** | **NO**  | :x: 

### What did you expect to see instead?

Consistency described above should be fixed.

`amount`:  field should be properly stored in DB (`amount_expected`) 
`destination_asset`/`source_asset` : field should be properly stored in DB, regardless of `quote_id` being set or not. Field should be accessible as a part of Platform Transaction. **Alternatively,** field should be forwarded in JWT.

### Suggested improvements

I think that logically this fields are closer to the `lang` parameter, than to `account`, in a sense that user MAY change this parameter in the UI. In the general UX, I would imagine this fields are only being pre-filled for the user, and they may change it later on in the UI. We don't need to store them, as finalized amount are already stored in amount_in/amount_out/amount_fee.
Instead, I suggest:
1. Store `amount` in DB (as we already have fields for it)  
2. Forward all 5 fields in JWT
3. Deprecate `amount_expected`
4. Describe in documentation which user request parameters are stored in DB, and which are forwarded in JWT
5. Remove  `amount_expected` in 3.0

**Comment by jopmiddelkamp** [comment]
When making a deposit we have `destination_asset` but with a withdrawal we have `source_asset` right?

**Comment by Ifropc** [comment]
Yep, updated

**Comment by JakeUrban** [comment]
Thanks for the detailed writeup @Ifropc!

I agree that we need to make our approach to storing transaction request data consistent. I suggest the following:

- all transaction data gets stored in the DB
- no transaction data gets stored in the JWT
- JWTs only have the transaction ID and requested lang
- we drop support for configuring additional fields to be added to the JWT (`txn_fields`)

Here is why I think this is the right approach:

- I don't see a benefit to _not_ saving the request's transaction data in the DB. The business will need to make an RPC request to update the transaction record at the end of the UI flow either way, so why not store the initial values? The business can overwrite them if the user updated the values in the UI.
- The purpose of the JWT is to enable the business to verify that the client has authenticated and that they initiated a specific transaction, not to provide transaction data. SEP-24 uses the POST method primarily to avoid passing KYC and transaction data in URLs, and we're effectively negating that design decision by including this data in the JWT
- Providing transaction data in the JWT is a minor convenience, saving the business an internal HTTP request (assuming the business doesn't need any additional transaction data from the DB). IMO that reason isn't compelling enough to support it

**Comment by Ifropc** [comment]
Totally agree, we should align our implementation to make it consistent. Also agree that storing transaction data in DB is a good solution.

However, I have some concerns about it:
* It complicates the flow a little bit. Developer would have 2 types of balance for each side of transaction (user input and the final amount), which might be confusing, as they would see both original value and final value in DB record.
* We shouldn't overwrite values. We have `amount_out` and `amount_in` for the purpose of providing users final amounts. 
* It adds extra values to Platform transaction which might not necessarily be supported by other protocols (such as SEP-31)
* It adds extra 3 calls in the flow: client -> backend; backend -> Platform server; Platform server -> DB in order to get data purely for interactive flow (i.e. this data will never be accessed later in the flow). With the exception of  the anchors that supports KYC pre-fill they would need to make a client -> backend call anyway
* Continuing previous point, we store data long-term that is not needed to be stored in such manner.
* We avoid passing KYC in JWT for a different reason. Transaction data is not sensitive and could be public.

I would prefer JWT approach, as I think it logically separates transaction user inputs that go into JWT, KYC that is delivered by the callback, and the rest of information that goes into Postgres.
That being said, I think approach with storing everything in DB is easier and might be more straight-forward, depending on how we design and document it.

**Comment by Ifropc** [comment]
> SEP-24 uses the POST method primarily to avoid passing KYC and transaction data in URLs

BTW technically speaking, we allow passing this data in query params

**Comment by JakeUrban** [comment]
> It complicates the flow a little bit. Developer would have 2 types of balance for each side of transaction (user input and the final amount)

The business will need to understand the distinction between the initially provided amount and the final amount regardless of how those amounts stored though.

> We shouldn't overwrite values. We have amount_out and amount_in for the purpose of providing users final amounts.

Updating transaction amounts based on user input seems like a pretty standard feature we should support. The RPC method `notify_interactive_flow_complete` allows for setting these values.

Also, I think the only field that will be overwritten in this case is the `amount_expected` field right?

**Comment by JakeUrban** [comment]
@lijamie98 I'm not opposed to keeping the txn_fields feature, but we should update it to use the API field names in 3.0

**Comment by lijamie98** [comment]
> @lijamie98 I'm not opposed to keeping the txn_fields feature, but we should update it to use the API field names in 3.0

@JakeUrban Do we already have the `txn_fields` API field name defined in v3.0?

**Comment by Ifropc** [comment]
I think Jake meant to use Platform Transaction field names, instead of DB transaction field names (which I also agree with, but it could be tricky to implement)

> Updating transaction amounts based on user input seems like a pretty standard feature we should support. The RPC method notify_interactive_flow_complete allows for setting these values.

Do you mean it SHOULD allow, or already allows? I understand that we want to keep both values, but what's the strategy of updating them? Do we update both user input and final value on `notify_interactive_flow_complete` and only allow updating final value on other RPC calls?

**Comment by JakeUrban** [comment]
> Do you mean it SHOULD allow, or already allows? I understand that we want to keep both values, but what's the strategy of updating them? Do we update both user input and final value on notify_interactive_flow_complete and only allow updating final value on other RPC calls?

The RPC API is designed such that specific methods are valid at specific points in the transaction lifecycle, and for each method, all parameters can be provided, meaning there are no cases where a method can be used but specific parameters of the method cannot (this approach removes complexity and makes the API easier to understand). This means that method parameters can overwrite previously set database values as long as the method is valid at that point in the transaction's lifecycle.

So, the `notify_interactive_flow_complete` method has an `amount_expected` parameter so that the business can set `amount_expected`, regardless of whether the database field associated with that parameter is already.

Another example is later in the flow, where `notify_onchain_funds_received` can be used to update everything but `amount_expected`, since it is possible that the client sends an unexpected amount, which would require a recalculation of the fees and payout.

> So, in concussion we should add all fields mentioned above in v2 to fill the gap (and update this fields automatically in notify_interactive_flow_complete). That also means we keep amount in JWT for backward compatibility.
>
> In v3 we remove all user input from JWT except lang, and re-design txn_fields to use platform transaction field notation vs current JDBC transaction field notation

That sounds good to me!

**Comment by Ifropc** [comment]
> So, the notify_interactive_flow_complete method has an amount_expected parameter so that the business can set amount_expected, regardless of whether the database field associated with that parameter is already set.

> Another example is later in the flow, where notify_onchain_funds_received can be used to update everything but amount_expected, since it is possible that the client sends an unexpected amount, which would require a recalculation of the fees and payout.

I think this could be the major source of the confusion. The developer will ask, "what's the difference between `amount_in` and `amount_expected` on the update?". Even in our RPC documentation they have the same description `"The amount expected in the payment".` And after interactive flow is complete they both serve the same purpose, to set amounts user what to send. Maybe we shouldn't allow to update both `amount_in` and `amount_expected`, if in the end they will hold the exact same value?  Wouldn't it be enough to just allow to update `amount_in` and set `amount_expected` equals to `amount_in` in `notify_interactive_flow_complete`? I agree that all other endpoints should NOT be allowed to update `amount_expected`. 
But in that case it feels like `amount_expected` is not even needed, if we already have `amount_in`. The reason we originally added it is because PATCH endpoint didn't have flexible enough validation, so if we reused amount_in, business was bug-prone into not updating amounts. Now, with RPC implemented, we always have this validation. 

And for the destination/source asset. Say, the user selects different assets from the one they provided in the request. That would mean, we either
* Have mismatch between `source_asset` and `amount_in.asset` 
* Update source asset and ALWAYS have a data duplication (we just store a field `source_asset` that we know will always equal to `amount_in.asset`)

**Comment by JakeUrban** [comment]
> I think this could be the major source of the confusion. The developer will ask, "what's the difference between amount_in and amount_expected on the update?". Even in our RPC documentation they have the same description "The amount expected in the payment".

This is a fair point. To clarify, the documentation is wrong and we should fix that. The purpose of `amount_expected` is to persist the _expected_ value to be received by the business. The expected value can change based on the user updating the amount prior to sending funds, and can differ from `amount_in` after funds are received.

The purpose of `amount_in` should be  persist the _actual_ value received by he business, and that is what it is once the business receives funds. But as you point out, prior to the business receiving funds, `amount_expected` and `amount_in` are the same, which is confusing. The alternative is to leave `amount_in` unset until payment has been received, but this doesn't make much sense because `amount_fee` and `amount_out` are set prior to receiving funds as well in order to communicate back to the client what the fee and ultimate payout is.

I think the ideal solution would have been something like this:

```js
{
  "expected_amounts": {
    "amount_in": "X",
   "amount_fee": "Y",
   "amount_out": "Z"
  },
  "actual_amounts": {
    "amount_in": "A",
    "amount_fee": "B",
    "amount_out": "C"
  }
}
```

While using the above structure in the SEP and platform transaction record would have been more clear, I think we can make do with the current schema as long as we make sure to clarity how amount fields work in our docs. And how they work is:

- Prior to funds being received, 
  - `amount_expected` and `amount_in` should have the same value
  - all amount fields are the _expected_ transaction amounts (based on `amount_expected`)
  - all amount fields (including `amount_expected`) can be updated depending on user input
- After funds are received, all amount fields except for `amount_expected` may be updated once more to reflect the actual transaction amounts

-------

On your comments about changes to the assets used, I'm not sure I understand the question. These fields should behave the same way `amount_in` behaves. The request values should be the initial values stored in the DB, and if the user changes the assets in the UI, the business can update them in the `notify_interactive_flow_complete` method.
