### ISSUE TITLE
When `lang` is not in the supported `languages` list, fall back to `en-US`

### ISSUE THREAD

**Issue by lijamie98** [stellar/java-stellar-anchor-sdk#280]
@lijamie98 thanks Jamie, I have the following suggestion for the description. Let me know if this makes sense to you:

When `lang` is not in the supported languages list, fall back to a default language - either `en` or `en-US` depending on the `lang` input format.

This is to update the `core-release-1.0` branch.

**Premises:**
1. if a `lang` using the `[language]`-only format is passed, we will always return `lang` using the same `[language]`-only format.
2. if a `lang` using the `[language]-[locale]` format is passed, we will always return `lang` using the same `[language]-[locale]` format.

^ I've added this since as per my experience integrating with Anchors if the `lang` **input** format is different than the `lang` **output** format this could potentially break things on their side. So just trying to keep it consistent here to play safe.

**Fall back mechanism**:
1. if a `lang` using the `[language]`-only format is unsupported, we will fall back to `en` value.
2. if a `lang` using the `[language]-[locale]` format is unsupported, we will find the first supported `lang` with the same `[language]-` prefix.
2.1 if no supported `lang` with the same `[language]-` prefix is found, we will fall back to `en-US`.

**For example:**
Supported langs: `["en", "es", "fr", "en-US", "en-CA", "es-ES", "fr-FR", "fr-CA", "zh-TW", "zh-CN", "uk-UA"]`
Requested langs:
- pt --> en
- uk --> en
- zh --> en
- en --> en
- es --> es
- fr --> fr
- fr-BE --> fr-FR
- fr-CA --> fr-CA
- zh-HK --> zh-TW
- es-AR --> es-ES
- uk-RU --> uk-UA
- pt-BR --> en-US
- en-UK --> en-US
- en-CA --> en-CA
- en-US --> en-US

**Comment by lijamie98** [comment]
Implemented in this commit: https://github.com/stellar/java-stellar-anchor-sdk/commit/ac11d437161e7f181f409b2d7fef2116fa4c71b1

**Comment by lijamie98** [comment]
Feedback from Cassio:

@lijamie98 thanks for implementing this fallback mechanism! I have some questions regarding how the AnchorSDK should handle different lang formats:

If I'm reading this correctly this means that if wallet passes lang using a simple format like uk, es, pt, etc. it'll throw this error which will trigger the en-US default language for all those cases. Is that correct?

If that's true, have we thought about making it more flexible so that Wallet and Anchors could also work with those simple (uk, es, pt) formats? The SEP says the default value for lang is en, so that makes me think we should probably also cover for the simple format. What do you think?

What I had in mind is something like this:

If wallet passes lang in the format uk, es, pt then the AnchorSDK will handle it considering only the language and also return something like uk, es, pt OR en as default language in case wallet passes an unsupported lang parameter

If wallet passes lang in the format uk-UA, es-AR, pt-BR then the AnchorSDK will handle it considering both the language + locale hence also returning something like uk-XX, es-XX, pt-XX OR en-US as default language in case wallet passes an unsupported lang parameter

Does that make sense?

I'm not sure which Anchors are using the SDK, but depending on the Anchor forcing an outcome in the en-US format could also possibly break things on their side.

Let me know what you think - thanks!

**Comment by CassioMG** [comment]
@lijamie98 thanks Jamie, I have the following suggestion for the description. Let me know if this makes sense to you:

When `lang` is not in the supported languages list, fall back to a default language - either `en` or `en-US` depending on the `lang` input format.

This is to update the `core-release-1.0` branch.

**Premises:**
1. if a `lang` using the `[language]`-only format is passed, we will always return `lang` using the same `[language]`-only format.
2. if a `lang` using the `[language]-[locale]` format is passed, we will always return `lang` using the same `[language]-[locale]` format.

^ I've added this since as per my experience integrating with Anchors if the `lang` **input** format is different than the `lang` **output** format this could potentially break things on their side. So just trying to keep it consistent here to play safe.

**Fall back mechanism**:
1. if a `lang` using the `[language]`-only format is unsupported, we will fall back to `en` value.
2. if a `lang` using the `[language]-[locale]` format is unsupported, we will find the first supported `lang` with the same `[language]-` prefix.
2.1 if no supported `lang` with the same `[language]-` prefix is found, we will fall back to `en-US`.

**For example:**
Supported langs: `["en", "es", "fr", "en-US", "en-CA", "es-ES", "fr-FR", "fr-CA", "zh-TW", "zh-CN", "uk-UA"]`
Requested langs:
- pt --> en
- uk --> en
- zh --> en
- en --> en
- es --> es
- fr --> fr
- fr-BE --> fr-FR
- fr-CA --> fr-CA
- zh-HK --> zh-TW
- es-AR --> es-ES
- uk-RU --> uk-UA
- pt-BR --> en-US
- en-UK --> en-US
- en-CA --> en-CA
- en-US --> en-US
