### ISSUE TITLE
Spring configs in yaml file not being honored by Anchor Platform

### ISSUE THREAD

**Issue by stfung77** [stellar/java-stellar-anchor-sdk#297]
Spring configs (defined in anchor-config-defuaults.yaml) are not being honored by the Anchor Platform application. Current work around is to set the config in AnchorPlatformServer.java 
ex: line 44 & 45
<img width="778" alt="image" src="https://user-images.githubusercontent.com/11511032/171948528-d022be61-8a4c-47e5-9ca7-929b5d671c68.png">

cc: @lijamie98

**Comment by marcelosalloum** [comment]
I think these configs are not being honored because we're bypassing the default configuration flow from spring boot.

I believe the fix for that is to manually inject the yaml properties as a spring boot source, like I did in this commit (that was not merged):
https://github.com/stellar/java-stellar-anchor-sdk/pull/334/commits/24d5a2cb8e03dc1d2a582f52432317c5e61ac29d#diff-c32d6fef3a0ecfcf799c1efbee4bad5b0f73c1cb82684e4c8adb7f4a6d9796f5R91-R94

```java
    ConfigurableEnvironment environment =
        (ConfigurableEnvironment) applicationContext.getEnvironment();
    for (PropertySource<?> source : sources) {
      environment.getPropertySources().addFirst(source);  // injecting the (yaml) source into the spring boot environments
```

**Comment by marcelosalloum** [comment]
@lijamie98: any thoughts?

**Comment by nirojapanda** [comment]
Can be tested along with #479
