### ISSUE TITLE
transaction-status-changed event sourceAccount and destioationAccount filled incorrectly

### ISSUE THREAD

**Issue by reecexlm** [stellar/java-stellar-anchor-sdk#388]
On `transaction-created` event, under `sourceAccount` and `destinationAccount` , the customers Anchor's UUID from `POST /transaction` are being sent:
https://github.com/stellar/java-stellar-anchor-sdk/blob/137b200c886345a0289b7eb6fe43e78e10452a66/core/src/main/java/org/stellar/anchor/sep31/Sep31Service.java#L176-L177

However, during `transaction-status-changed`, those fields are being populated with stellar accounts from the observed blockchain payment:
https://github.com/stellar/java-stellar-anchor-sdk/blob/0ab3db136ccf256294b05082271b23559844be33/platform/src/main/java/org/stellar/anchor/platform/service/PaymentOperationToEventListener.java#L193-L194

--

> This is a blocker,. for now a temporary workaround this issue by ignoring the source and destination account coming in transaction-status-changed and use the UUIDs we got from the first transaction-created.

**Comment by marcelosalloum** [comment]
It'd be great to also update the documentation explaining the source_account and destination_account refer to the SEP-12 user ID, rather than the accounts on the Stellar network:

https://github.com/stellar/java-stellar-anchor-sdk/blob/20abf59472c48783bcb3476d338cee57c7be50b4/docs/03%20-%20Implementing%20the%20Anchor%20Server/Communication/Events%20Schema.yml#L161-L164

**Comment by stfung77** [comment]
closed with - https://github.com/stellar/java-stellar-anchor-sdk/pull/395
