### ISSUE TITLE
Payment Observer Got Stuck

### ISSUE THREAD

**Issue by reecexlm** [stellar/java-stellar-anchor-sdk#701]
Investigate why Payment Observer got stuck.  This instance payment observer was not running as a separate service.  Part of this investigation should make sure this scenario would be covered by payment observer running as a separate k8s healthcheck.
Logs included in Jira. ANCHOR-129

**Comment by lijamie98** [comment]
In order for the /health endpoint to report error for the observer, it must be running in a separated service.

I had also investigated the cause of the long catch-up time. The observer reads the last cursor (eg: 189720666949242920) stored in the database, then tries to catch up from the last cursor. The longer the observer is stuck, the longer it takes to read from the production network.

We reduced the problem in the develop branch: [StellarPaymentObserver.java](https://github.com/stellar/java-stellar-anchor-sdk/blob/3054e1e3b8d990bf016b53ce49b4cf60558c55dc/platform/src/main/java/org/stellar/anchor/platform/observer/stellar/StellarPaymentObserver.java#L277)#277, so that the observer only reads up to the most recent MAX_RESULT (200) transactions instead of from the last known cursor.
The fix also handles the testnet reset. (edited)
